analytics:
  ga_prod: UA-42145528-4
baseurl: /sdg-indicators
branch: gh-pages
collections:
  goals:
    output: true
  indicators:
    output: true
  pages:
    output: true
    permalink: /:path/
country:
  adjective: TEST
  name: TEST
data_dir: data
description: Data Platform Prototype
email_contacts:
  functional: email@email.com
  questions: email@email.com
  suggestions: email@email.com
exclude:
- vendor
markdown: kramdown
org_name: TEST
prose:
  ignore:
  - /assets
  - /_includes
  - /_layouts
  - /scripts
  - /sass
  metadata:
    _indicators:
    - field:
        element: text
        label: Indicator Name
        scope: global
      name: indicator_name
    - field:
        element: hidden
        label: Indicator Number
        scope: global
      name: indicator
    - field:
        element: text
        label: Target Name
        scope: global
      name: target
    - field:
        element: text
        label: Target Number
        scope: global
      name: target_id
    - field:
        element: textarea
        label: Global Indicator Description
        scope: global
      name: indicator_definition
    - field:
        element: text
        label: UN Designated Tier
        scope: global
      name: un_designated_tier
    - field:
        element: text
        label: UN Custodian Agency
        scope: global
      name: un_custodian_agency
    - field:
        element: text
        label: Link to UN Metadata
        scope: global
      name: goal_meta_link
    - field:
        element: text
        label: Link to UN Metadata Text
        scope: global
        value: UN Metadata
      name: goal_meta_link_text
    - field:
        element: text
        label: Actual Indicator Available
        scope: national
      name: national_indicator_available
    - field:
        element: text
        label: Actual Indicator Description
        scope: national
      name: national_indicator_description
    - field:
        element: text
        label: Indicator Periodicity
        scope: national
      name: national_indicator_periodicity
    - field:
        element: text
        label: Earliest Available Data
        scope: national
      name: national_earliest_available_data
    - field:
        element: text
        label: Geographic Coverage
        scope: national
      name: national_geographical_coverage
    - field:
        element: text
        help: A date in YYYY-MM-DD format
        label: Release Date
        placeholder: YYYY-MM-DD
        scope: national
      name: admin_release_date
    - field:
        element: text
        help: A date in YYYY-MM-DD format
        label: Next Release
        placeholder: YYYY-MM-DD
        scope: national
      name: admin_next_release
    - field:
        element: text
        label: Statistical Classification
        scope: national
      name: admin_statistical_classification
    - field:
        element: text
        label: Disaggregation
        scope: national
      name: computation_disaggregation
    - field:
        element: text
        label: Comments and Limitations
        scope: national
      name: comments_limitations
    - field:
        element: text
        label: Contact Details
        scope: national
      name: admin_contact_details
    - field:
        element: text
        label: Units of Measure
        scope: computation
      name: computation_units
    - field:
        element: text
        label: Calculations
        scope: computation
      name: computation_calculations
    - field:
        element: text
        label: Numerator
        scope: computation
      name: computation_numerator
    - field:
        element: text
        label: Denominator
        scope: computation
      name: computation_denominator
    - field:
        element: textarea
        label: Definitions
        scope: computation
      name: computation_definitions
    - field:
        element: checkbox
        help: Whether or not to display this source
        label: Source 1 Active
        value: true
      name: source_active_1
    - field:
        element: text
        label: Organisation
        scope: source_1
      name: source_organisation_1
    - field:
        element: text
        label: Periodicity
        scope: source_1
      name: source_periodicity_1
    - field:
        element: text
        label: Earliest Available Data
        scope: source_1
      name: source_earliest_available_1
    - field:
        element: text
        label: Geographical Coverage
        scope: source_1
      name: source_geographical_coverage_1
    - field:
        element: text
        label: Link to Data Source
        scope: source_1
      name: source_url_1
    - field:
        element: text
        label: Link to Data Source Text
        scope: source_1
        value: Link to Source
      name: source_url_text_1
    - field:
        element: text
        help: A date in YYYY-MM-DD format
        label: Release Date
        placeholder: YYYY-MM-DD
        scope: source_1
      name: source_release_date_1
    - field:
        element: text
        help: A date in YYYY-MM-DD format
        label: Next Release
        placeholder: YYYY-MM-DD
        scope: source_1
      name: source_next_release_1
    - field:
        element: text
        label: Statistical Classification
        scope: source_1
      name: source_statistical_classification_1
    - field:
        element: text
        label: Contact Details
        scope: source_1
      name: source_contact_1
    - field:
        element: textarea
        label: Other Information
        scope: source_1
      name: source_other_info_1
    - field:
        element: checkbox
        help: Whether or not to display this source
        label: Source 2 Active
        value: false
      name: source_active_2
    - field:
        element: text
        label: Organisation
        scope: source_2
      name: source_organisation_2
    - field:
        element: text
        label: Periodicity
        scope: source_2
      name: source_periodicity_2
    - field:
        element: text
        label: Earliest Available Data
        scope: source_2
      name: source_earliest_available_2
    - field:
        element: text
        label: Geographical Coverage
        scope: source_2
      name: source_geographical_coverage_2
    - field:
        element: text
        label: Link to Data Source
        scope: source_2
      name: source_url_2
    - field:
        element: text
        label: Link to Data Source Text
        scope: source_2
        value: Link to Source
      name: source_url_text_2
    - field:
        element: text
        help: A date in YYYY-MM-DD format
        label: Release Date
        placeholder: YYYY-MM-DD
        scope: source_2
      name: source_release_date_2
    - field:
        element: text
        help: A date in YYYY-MM-DD format
        label: Next Release
        placeholder: YYYY-MM-DD
        scope: source_2
      name: source_next_release_2
    - field:
        element: text
        label: Statistical Classification
        scope: source_2
      name: source_statistical_classification_2
    - field:
        element: text
        label: Contact Details
        scope: source_2
      name: source_contact_2
    - field:
        element: textarea
        label: Other Information
        scope: source_2
      name: source_other_info_2
    - field:
        element: checkbox
        help: Whether or not to display this source
        label: Source 3 Active
        value: false
      name: source_active_3
    - field:
        element: text
        label: Organisation
        scope: source_3
      name: source_organisation_3
    - field:
        element: text
        label: Periodicity
        scope: source_3
      name: source_periodicity_3
    - field:
        element: text
        label: Earliest Available Data
        scope: source_3
      name: source_earliest_available_3
    - field:
        element: text
        label: Geographical Coverage
        scope: source_3
      name: source_geographical_coverage_3
    - field:
        element: text
        label: Link to Data Source
        scope: source_3
        value: Link to Source
      name: source_url_3
    - field:
        element: text
        label: Link to Data Source Text
        scope: source_3
      name: source_url_text_3
    - field:
        element: text
        help: A date in YYYY-MM-DD format
        label: Release Date
        placeholder: YYYY-MM-DD
        scope: source_3
      name: source_release_date_3
    - field:
        element: text
        help: A date in YYYY-MM-DD format
        label: Next Release
        placeholder: YYYY-MM-DD
        scope: source_3
      name: source_next_release_3
    - field:
        element: text
        label: Statistical Classification
        scope: source_3
      name: source_statistical_classification_3
    - field:
        element: text
        label: Contact Details
        scope: source_3
      name: source_contact_3
    - field:
        element: textarea
        label: Other Information
        scope: source_3
      name: source_other_info_3
    - field:
        element: text
        label: Data Hierachy Edge List
      name: data_edge_list
    - field:
        element: select
        label: Graph Type
        options:
        - name: Longitudinal
          value: Longitudinal
        - name: Bar
          value: Bar
      name: graph_type
    - field:
        element: text
        label: Graph Title
      name: graph_title
repo_name: sdg-indicators
title: U.K. Indicators For The Sustainable Development Goals
url: ''
