analytics:
  ga_prod: UA-42145528-4
baseurl: ''
branch: gh-pages
collections:
  goals:
    output: true
  indicators:
    output: true
  pages:
    output: true
    permalink: /:path/
data_dir: data
description: Data Platform Prototype
email_contacts:
  functional: email@email.com
  questions: email@email.com
  suggestions: email@email.com
exclude:
- vendor
markdown: kramdown
org_name: TEST
prose:
  ignore:
  - /assets
  - /_includes
  - /_layouts
  - /scripts
  - /sass
  metadata:
    _indicators:
    - field:
        element: text
        label: SDG Indicator Name
        scope: global
      name: indicator_name
    - field:
        element: text
        label: SDG Target Addressed
        scope: global
      name: target
    - field:
        element: textarea
        label: Definition of SDG Indicator
        scope: global
      name: indicator_definition
    - field:
        element: textarea
        label: Method of computation for global SDG indicator
        scope: global
      name: method_of_computation
    - field:
        element: text
        label: UN Designated Tier
        scope: global
      name: un_designated_tier
    - field:
        element: text
        label: UN Custodial Agency
        scope: global
      name: un_custodian_agency
    - field:
        element: text
        label: Graph Title
      name: graph_title
    - field:
        element: text
        label: Actual indicator available
      name: actual_indicator_available
    - field:
        element: textarea
        label: Description of actual indicator available
      name: actual_indicator_available_description
    - field:
        element: textarea
        label: Method of computation
      name: us_method_of_computation
    - field:
        element: textarea
        label: Comments and limitations
      name: comments_and_limitations
    - field:
        element: text
        label: Periodicity
      name: periodicity
    - field:
        element: text
        label: Time Period
      name: time_period
    - field:
        element: text
        label: Unit of measure
      name: unit_of_measure
    - field:
        element: text
        label: 'Disaggregation #1 (Industry or social categories)'
      name: disaggregation_categories
    - field:
        element: text
        label: 'Disaggregation #2 (Geographical coverage)'
      name: disaggregation_geography
    - field:
        element: text
        label: Date of public data release from National source
        placeholder: MONTH YEAR
      name: date_of_national_source_publication
    - field:
        element: text
        label: Date of last Update of This Page
        placeholder: MONTH YEAR
      name: date_metadata_updated
    - field:
        element: text
        label: Scheduled Update by National source
        placeholder: MONTH/YEAR (Next Agency Release)
      name: scheduled_update_by_national_source
    - field:
        element: text
        label: Scheduled Update by SDG Team
        placeholder: MONTH/YEAR (NRP Database)
      name: scheduled_update_by_SDG_team
    - field:
        element: text
        label: Data Source1 (Agency STAFF NAME)
      name: source_agency_staff_name
    - field:
        element: text
        label: Data Source2 (Staff E-MAIL)
      name: source_agency_staff_email
    - field:
        element: text
        label: Data Source3 (Agency/Survey/Dataset name)
      name: source_agency_survey_dataset
    - field:
        element: text
        label: Indicator web address (closest to data provided)
      name: source_url
    - field:
        element: text
        label: International and National References
      name: international_and_national_references
repo_name: sdg-indicators
title: U.K. Indicators For The Sustainable Development Goals
url: ''
